#!/usr/bin/env python
"""Regenerate days/INDEX.md - one row per written part document.

Why this exists: the standalone test (plan §24.4) says a part must name and link its
prerequisite rather than assume it. 152 days is long enough that Day 26 is genuinely
forgotten by Day 124, and the only way to link to where an idea was already taught is to
be able to find it without opening every day. This is that lookup.

Like docs/TRACKER.md it is a **projection** - every cell is copied from a part's own
frontmatter. Regenerated by `./m tracker`; never edited by hand.
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DAYS = ROOT / "days"


def frontmatter(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return out
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" in line and not line.startswith((" ", "\t", "-")):
            k, _, v = line.partition(":")
            out[k.strip()] = v.strip().strip("\"'")
    return out


def main() -> int:
    if not DAYS.is_dir():
        print("no days/ directory yet - nothing to index")
        return 0

    out: list[str] = [
        "---",
        "name: parts-index",
        "plan: jala",
        f'generated: "{date.today().isoformat()}"',
        "generator: scripts/parts_index.py",
        "---",
        "",
        "# 🗂️ Parts index — every written sub-topic document",
        "",
        "> **Do not edit this file by hand.** It is regenerated by `./m tracker` from the "
        "frontmatter of\n> every part under `days/day-NNN-<slug>/parts/`. Every cell is "
        "copied; nothing here is written\n> independently of the parts themselves.",
        "",
        "> **What this is for.** One row per part, so a later day can find where an idea "
        "was already\n> taught and **link to it** instead of explaining it twice — the "
        "standalone test, plan §24.4.\n> The second table inverts it: which part serves "
        "which curriculum ID.",
        "",
    ]

    by_id: dict[str, list[str]] = {}
    total = 0

    for day_dir in sorted(DAYS.iterdir()):
        if not (day_dir.is_dir() and re.fullmatch(r"day-\d{3}-.*", day_dir.name)):
            continue
        parts_dir = day_dir / "parts"
        if not parts_dir.is_dir():
            continue
        files = sorted(parts_dir.rglob("*.md"), key=lambda p: (p.parent.name, p.name))
        if not files:
            continue

        out.append(f"## `{day_dir.name}` — {len(files)} parts")
        out.append("")
        out.append("| Part | Level | Tier | Title | IDs | File |")
        out.append("| --- | --- | --- | --- | --- | --- |")
        for f in files:
            fm = frontmatter(f)
            rel = f.relative_to(day_dir).as_posix()
            href = f"{day_dir.name}/{rel}"
            num = fm.get("part", f.stem.split("-")[0])
            title = fm.get("title", f.stem)
            ids = fm.get("ids", "[]")
            out.append(
                f"| {num} | {fm.get('level', '?')} | {fm.get('tier', '?')} | {title} "
                f"| {ids} | [`{rel}`]({href}) |"
            )
            total += 1
            for cid in re.findall(r"[A-Z]+-\d{2}", ids):
                by_id.setdefault(cid, []).append(f"[{day_dir.name} {num}]({href})")
        out.append("")

    out.append("## Which part serves which curriculum ID")
    out.append("")
    if by_id:
        out.append("| ID | Parts |")
        out.append("| --- | --- |")
        for cid in sorted(by_id):
            out.append(f"| `{cid}` | {' · '.join(by_id[cid])} |")
    else:
        out.append("No part declares a curriculum ID yet — Day 0 closes none, by design.")
    out.append("")

    (DAYS / "INDEX.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote days/INDEX.md ({total} parts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
