#!/usr/bin/env python
"""Regenerate docs/TRACKER.md and docs/CURRICULUM_INDEX.md (plan §26).

Both are **projections**: every cell is copied from either the day map in
`scripts/plan_check.py` or the frontmatter of a day that is actually on disk. Nothing here
is written independently of its source, which is the only reason either file is allowed to
stand in for reading its source. They are regenerated by `./m tracker` and never edited by
hand - editing one only means the next `./m check` silently overwrites you.

Run with `--summary` for the one-line progress that `./m status` prints.
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from plan_check import PHASES, closes_on  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DAYS = ROOT / "days"
DOCS = ROOT / "docs"

DO_NOT_EDIT = (
    "> **Do not edit this file by hand.** It is regenerated by `./m tracker` from the day "
    "map in\n> `scripts/plan_check.py` and from what is actually on disk under `days/`. "
    "Every cell is copied;\n> nothing here is written independently of its source.\n"
)


def day_dirs() -> dict[int, Path]:
    """Every written day, by number. The number is the identity; the slug is a label."""
    out: dict[int, Path] = {}
    if not DAYS.is_dir():
        return out
    for d in sorted(DAYS.iterdir()):
        m = re.fullmatch(r"day-(\d{3})-.*", d.name) if d.is_dir() else None
        if m:
            out[int(m.group(1))] = d
    return out


def part_count(day_dir: Path) -> int:
    parts = day_dir / "parts"
    if not parts.is_dir():
        return 0
    return sum(1 for f in parts.rglob("*.md"))


def frontmatter(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return out
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" in line and not line.startswith((" ", "\t", "-")):
            k, _, v = line.partition(":")
            out[k.strip()] = v.strip().strip("\"'")
    return out


def completed_days() -> set[int]:
    """Day numbers with a row in the append-only progress ledger (§26)."""
    progress = DOCS / "PROGRESS.md"
    if not progress.exists():
        return set()
    out: set[int] = set()
    for line in progress.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\|\s*(\d{1,3})\s*\|", line)
        if m:
            out.add(int(m.group(1)))
    return out


def build_tracker() -> str:
    written = day_dirs()
    done = completed_days()
    total_days = sum(len(p.days) for p in PHASES)

    out: list[str] = [
        "---",
        "name: tracker",
        "plan: jala",
        f'generated: "{date.today().isoformat()}"',
        "generator: scripts/tracker.py",
        "---",
        "",
        "# 📊 Tracker — what is written, and what is pending",
        "",
        DO_NOT_EDIT,
        "> **How many parts a day has is the thin-day detector.** A day that is written but "
        "carries\n> three parts is visible from this table alone (plan §24.10).",
        "",
        f"**{len(done)} of {total_days} days complete · {len(written)} written on disk · "
        f"{sum(part_count(d) for d in written.values())} part documents.**",
        "",
    ]

    for phase in PHASES:
        ns = [d.n for d in phase.days]
        span = f"Day {ns[0]}" if len(ns) == 1 else f"Days {ns[0]}–{ns[-1]}"
        phase_written = sum(1 for d in phase.days if d.n in written)
        out.append(f"## Phase {phase.n} — {phase.name} ({span})")
        out.append("")
        out.append(f"**Gate:** {phase.gate}")
        out.append("")
        out.append(f"**Written:** {phase_written} / {len(phase.days)}")
        out.append("")
        out.append("| Day | Status | Parts | Title | IDs |")
        out.append("| --- | --- | --- | --- | --- |")
        for day in phase.days:
            d = written.get(day.n)
            if day.n in done:
                status = "✅ complete"
            elif d is not None:
                status = "✍️ written"
            else:
                status = "— pending"
            parts = str(part_count(d)) if d is not None else "—"
            title = f"[{day.title}](../days/{d.name}/LESSON.md)" if d else day.title
            ids = ", ".join(f"`{i}`" for i in day.ids) or "—"
            out.append(f"| {day.n} | {status} | {parts} | {title} | {ids} |")
        out.append("")

    return "\n".join(out) + "\n"


def build_curriculum_index() -> str:
    """The ID → day cross-table. Answers 'where do I learn TRANS-17?' (§26)."""
    from plan_check import CURRICULA

    written = day_dirs()
    where = closes_on()

    out: list[str] = [
        "---",
        "name: curriculum-index",
        "plan: jala",
        f'generated: "{date.today().isoformat()}"',
        "generator: scripts/tracker.py",
        "---",
        "",
        "# 🧭 Curriculum index — every concept ID and the day that closes it",
        "",
        DO_NOT_EDIT,
        "",
    ]

    for prefix, (name, concepts) in CURRICULA.items():
        out.append(f"## `{prefix}` — {name}")
        out.append("")
        out.append("| ID | Concept | Closes on | Written |")
        out.append("| --- | --- | --- | --- |")
        for i, concept in enumerate(concepts, start=1):
            cid = f"{prefix}-{i:02d}"
            n = where[cid]
            d = written.get(n)
            link = f"[Day {n}](../days/{d.name}/LESSON.md)" if d else f"Day {n}"
            out.append(f"| `{cid}` | {concept} | {link} | {'yes' if d else 'no'} |")
        out.append("")

    return "\n".join(out) + "\n"


def summary() -> str:
    written = day_dirs()
    done = completed_days()
    total = sum(len(p.days) for p in PHASES)
    if not done:
        return f"no day completed yet — {len(written)} written of {total}"
    last = max(done)
    d = written.get(last)
    slug = d.name if d else f"day-{last:03d}"
    return (
        f"last completed: day {last} ({slug}) · "
        f"{len(done)}/{total} complete · {len(written)} written"
    )


def main() -> int:
    if "--summary" in sys.argv:
        print(summary())
        return 0
    DOCS.mkdir(parents=True, exist_ok=True)
    (DOCS / "TRACKER.md").write_text(build_tracker(), encoding="utf-8")
    (DOCS / "CURRICULUM_INDEX.md").write_text(build_curriculum_index(), encoding="utf-8")
    print("wrote docs/TRACKER.md, docs/CURRICULUM_INDEX.md")
    print(summary())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
